"use client";

import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Bot, Loader2, Voicemail } from "lucide-react";

import { generateReportFromVoice } from "@/ai/flows/voice-activated-reporting";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";

const formSchema = z.object({
  voiceCommand: z.string().min(10, "Please provide a more detailed command."),
});

export function VoiceReportingClient() {
  const [audioSrc, setAudioSrc] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      voiceCommand: "",
    },
  });

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true);
    setAudioSrc(null);
    try {
      const res = await generateReportFromVoice(values);
      setAudioSrc(res.reportAudio);
    } catch (error) {
      console.error(error);
      toast({
        title: "Error",
        description: "Failed to generate audio report. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <div className="grid gap-8 md:grid-cols-2">
      <Card>
        <CardHeader>
          <CardTitle>Voice-Activated Reporting</CardTitle>
          <CardDescription>
            Enter a command to generate an audio report.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
              <FormField
                control={form.control}
                name="voiceCommand"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Voice Command (enter as text)</FormLabel>
                    <FormControl>
                      <Textarea placeholder="e.g., 'Generate a status report for the Downtown Tower project focusing on material usage this week.'" {...field} rows={4} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <Button type="submit" disabled={isLoading} className="w-full">
                {isLoading ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <Voicemail className="mr-2 h-4 w-4" />
                )}
                Generate Audio Report
              </Button>
            </form>
          </Form>
        </CardContent>
      </Card>

      <div className="space-y-4">
        <Card>
          <CardHeader>
            <CardTitle>Generated Audio Report</CardTitle>
            <CardDescription>
              Listen to the report generated by the AI.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            {isLoading && (
              <div className="flex items-center justify-center p-8">
                <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
              </div>
            )}
            {audioSrc ? (
              <audio controls src={audioSrc} className="w-full">
                Your browser does not support the audio element.
              </audio>
            ) : (
              !isLoading && (
                <div className="text-center text-sm text-muted-foreground p-8">
                  Your audio report will appear here.
                </div>
              )
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
